# Generated by Django 5.2.1 on 2025-06-05 02:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Congregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TerritoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VisitStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('label', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Code는 NN-NN-NN의 형식이어야 합니다. 각각의 NN은 01-99까지의 숫자 가운데 하나여야 합니다.', regex='^(0[1-9]|[1-9][0-9])-(0[1-9]|[1-9][0-9])-(0[1-9]|[1-9][0-9])$)')])),
                ('address1', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255)),
                ('address_detail', models.CharField(blank=True, max_length=255)),
                ('note', models.TextField(blank=True, help_text='구역에 대한 상세 메모', null=True)),
                ('in_use', models.BooleanField(default=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_territories', to=settings.AUTH_USER_MODEL)),
                ('congregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='territory.congregation')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='territories', to='territory.territorycategory')),
            ],
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('territory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_histories', to='territory.territory')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='visit_histories', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='territory.visitstatus')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('territory', 'visited_at', 'status'), name='unique_territory_visit')],
            },
        ),
    ]
