# Generated by Django 5.2.1 on 2025-06-07 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
        ('territory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='deck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='territories', to='deck.deck'),
        ),
    ]
