# Generated by Django 5.2.1 on 2025-06-09 11:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0002_territory_deck'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOverseer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='congregation',
            name='address',
            field=models.CharField(blank=True, max_length=124, null=True),
        ),
        migrations.AlterField(
            model_name='territory',
            name='code',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='Code는 NN-NN-NN의 형식이어야 합니다. 각각의 NN은 01-99까지의 숫자 가운데 하나여야 합니다.', regex='^(0[1-9]|[1-9][0-9])-(0[1-9]|[1-9][0-9])-(0[1-9]|[1-9][0-9])$')]),
        ),
        migrations.AddField(
            model_name='congregation',
            name='service_overseer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='territory.serviceoverseer'),
        ),
    ]
