# Generated by Django 5.2.1 on 2025-06-09 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory', '0003_serviceoverseer_congregation_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congregation',
            name='service_overseer',
        ),
        migrations.AddField(
            model_name='serviceoverseer',
            name='congregation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_overseer', to='territory.congregation'),
        ),
    ]
