# Generated by Django 5.2.1 on 2025-06-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_group_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bg_color',
            field=models.CharField(default='bg-stone-100', max_length=64),
        ),
        migrations.AddField(
            model_name='group',
            name='text_color',
            field=models.CharField(default='text-gray-700', max_length=64),
        ),
    ]
