# Generated by Django 5.2.1 on 2025-06-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_group_bg_color_group_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='tile_bg_color',
            field=models.CharField(default='bg-amber-50', max_length=64),
        ),
    ]
