# Generated by Django 5.2.1 on 2025-06-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_group_tile_bg_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='symbol',
            field=models.CharField(default='🌳', max_length=10),
        ),
    ]
