# Generated by Django 5.2.1 on 2026-07-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_group_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
