# Generated by Django 5.2.1 on 2026-07-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_member_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
