# Generated by Django 5.2.1 on 2026-07-23 04:47

import apps.member.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0010_member_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default=apps.member.models.unusable_password_hash, max_length=128),
        ),
    ]
