# Generated by Django 5.2.1 on 2026-08-30 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_alter_member_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='가족명')),
                ('active', models.BooleanField(default=True, verbose_name='활성')),
            ],
            options={
                'verbose_name': '가족',
                'verbose_name_plural': '가족',
            },
        ),
        migrations.CreateModel(
            name='FamilyRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='역할명')),
                ('is_guardian', models.BooleanField(default=False, help_text='켜면 이 역할의 성원이 가족 내 자녀의 성구 스탬프 등을 관리할 수 있습니다.', verbose_name='보호자 권한')),
            ],
            options={
                'verbose_name': '가족 역할',
                'verbose_name_plural': '가족 역할',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='member.family', verbose_name='가족'),
        ),
        migrations.AddField(
            model_name='member',
            name='family_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='members', to='member.familyrole', verbose_name='가족 역할'),
        ),
    ]
