# Generated by Django 5.2.1 on 2026-08-03 00:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_id', models.PositiveSmallIntegerField(verbose_name='읽기 단위 ID')),
                ('read_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='읽은 날짜')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bible_reading_progress', to=settings.AUTH_USER_MODEL, verbose_name='멤버')),
            ],
            options={
                'verbose_name': '성경 읽기 진도',
                'verbose_name_plural': '성경 읽기 진도',
                'constraints': [models.UniqueConstraint(fields=('member', 'unit_id'), name='uniq_bible_reading_member_unit')],
            },
        ),
    ]
