# Generated by Django 5.2.1 on 2025-06-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='cmd',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='command',
            name='desc',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
