# Generated by Django 5.2.1 on 2025-06-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_command_cmd_command_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='command',
            name='cmd',
        ),
        migrations.AddField(
            model_name='command',
            name='url_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
