# Generated by Django 5.2.1 on 2026-08-22 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_link_code', to=settings.AUTH_USER_MODEL, verbose_name='멤버')),
            ],
            options={
                'verbose_name': '연결 초대코드',
                'verbose_name_plural': '연결 초대코드',
            },
        ),
        migrations.CreateModel(
            name='MessengerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('line', 'LINE')], default='line', max_length=16, verbose_name='메신저')),
                ('provider_user_id', models.CharField(max_length=64, verbose_name='메신저 사용자 ID')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='표시 이름')),
                ('picture_url', models.URLField(blank=True, verbose_name='프로필 이미지')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_accounts', to=settings.AUTH_USER_MODEL, verbose_name='멤버')),
            ],
            options={
                'verbose_name': '메신저 계정',
                'verbose_name_plural': '메신저 계정',
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='unique_messenger_account'), models.UniqueConstraint(fields=('member', 'provider'), name='unique_member_provider')],
            },
        ),
    ]
