# Generated by Django 5.2.1 on 2026-08-22 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_copy_from_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkCodeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('line', 'LINE')], max_length=16, verbose_name='메신저')),
                ('provider_user_id', models.CharField(max_length=64, verbose_name='메신저 사용자 ID')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='표시 이름')),
                ('message', models.TextField(verbose_name='요청 메시지')),
                ('status', models.CharField(choices=[('pending', '대기'), ('issued', '발급됨')], default='pending', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('issued_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='발급된 멤버')),
            ],
            options={
                'verbose_name': '초대코드 요청',
                'verbose_name_plural': '초대코드 요청',
                'ordering': ['-created_at'],
            },
        ),
    ]
