"""
Django settings for tsk project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ─────────────────────────────────────────────────────────────
# 환경변수 (django-environ)
# BASE_DIR/.env 파일이 있으면 읽어서 os.environ 에 로드한다(없으면 조용히 넘어감).
# 시크릿·환경별 설정은 .env 로 분리한다. 템플릿은 .env.example 참고.
# ─────────────────────────────────────────────────────────────
env = environ.Env(
    DEBUG=(bool, False),                 # 기본값은 운영 안전값(False)
    ALLOWED_HOSTS=(list, ["*"]),
    CSRF_TRUSTED_ORIGINS=(list, []),
)
environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# .env 에 SECRET_KEY 미설정 시 기동마다 랜덤 키 생성(세션이 재시작마다 무효화됨).
# 운영에서는 반드시 .env 에 고정 키를 설정할 것.
from django.core.management.utils import get_random_secret_key

SECRET_KEY = env("SECRET_KEY", default="") or get_random_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!
# 포트폴리오 스냅샷: .env 없이도 바로 띄워볼 수 있도록 기본 True (운영은 False 로).
DEBUG = env.bool("DEBUG", default=True)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")
CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS")
SECURE_PROXY_SSL_HEADER = ['HTTP_X_FORWARDED_PROTO', 'https']

# ─────────────────────────────────────────────────────────────
# LINE MINI App / LIFF 연동 설정
# 시크릿은 코드에 두지 말고 환경변수로 주입한다.
#   LINE_LIFF_ID      : 프론트(LIFF SDK)에서 사용하는 LIFF ID
#   LINE_CHANNEL_ID   : ID Token 검증 시 aud 확인에 사용하는 채널 ID
# 둘 중 하나라도 비어 있으면 LINE 로그인이 비활성화되며,
# DEBUG=True 인 경우에 한해 개발용 우회 로그인(멤버 직접 선택)이 허용된다.
# ─────────────────────────────────────────────────────────────
# 화면에 표시할 회중(조직) 이름 — 코드에 하드코딩하지 않고 환경변수로 주입.
CONGREGATION_NAME = env('CONGREGATION_NAME', default='회중')

LINE_LIFF_ID = env('LINE_LIFF_ID', default='')
LINE_CHANNEL_ID = env('LINE_CHANNEL_ID', default='')

# LINE 로그인 사용 가능 여부(프론트/뷰에서 분기용)
LINE_LOGIN_ENABLED = bool(LINE_LIFF_ID and LINE_CHANNEL_ID)

# LINE 미설정 + DEBUG 환경에서만 개발용 우회 로그인을 허용
LINE_DEV_LOGIN = DEBUG and not LINE_LOGIN_ENABLED

# ─────────────────────────────────────────────────────────────
# LINE Messaging API (공식어카운트 봇 — 그룹채팅 키워드 → Flex 메뉴)
# LIFF(LINE Login 채널)와는 별개인 Messaging API 채널의 시크릿/토큰.
#   LINE_MESSAGING_CHANNEL_SECRET : 웹훅 서명(X-Line-Signature) 검증용
#   LINE_MESSAGING_ACCESS_TOKEN   : Reply API 호출용 (long-lived)
#   SITE_BASE_URL                 : Flex 메시지 이미지 절대 URL 조립용 (https://<도메인>, 끝 슬래시 없이)
# 둘 중 하나라도 비어 있으면 웹훅이 비활성화(404)된다.
# ─────────────────────────────────────────────────────────────
LINE_MESSAGING_CHANNEL_SECRET = env('LINE_MESSAGING_CHANNEL_SECRET', default='')
LINE_MESSAGING_ACCESS_TOKEN = env('LINE_MESSAGING_ACCESS_TOKEN', default='')
SITE_BASE_URL = env('SITE_BASE_URL', default='').rstrip('/')

LINE_BOT_ENABLED = bool(LINE_MESSAGING_CHANNEL_SECRET and LINE_MESSAGING_ACCESS_TOKEN)

# 로그인/리다이렉트 대상 (미인증 접근 시 LINE 로그인 진입점으로)
LOGIN_URL = 'line:entry'
# 봉사자의 기본 첫 화면은 구역카드(구글시트) 앱. 기존 DB 화면(territory)은 URL 직접 접근으로 공존.
LOGIN_REDIRECT_URL = 'territory_cards:card_list'

# ─────────────────────────────────────────────────────────────
# territory_cards (구역카드 = 구글시트) 연동 설정
# 구역 데이터의 소스는 DB 가 아니라 구글시트다. 서비스 계정으로 Sheets API 접근.
# 시크릿은 코드에 두지 말고 .env 로 주입한다.
#   GOOGLE_SERVICE_ACCOUNT_FILE : 서비스계정 키 JSON 파일 경로, 또는
#   GOOGLE_SERVICE_ACCOUNT_JSON : 키 JSON 문자열 그 자체(파일 경로 대신)
#   TERRITORY_CARDS_MASTER_SHEET_ID : 마스터 인덱스("시트리스트_시트")의 spreadsheetId
# 대상 시트들은 서비스 계정 이메일에 미리 "공유"해두어야 한다.
# ─────────────────────────────────────────────────────────────
GOOGLE_SERVICE_ACCOUNT_FILE = env('GOOGLE_SERVICE_ACCOUNT_FILE', default='')
GOOGLE_SERVICE_ACCOUNT_JSON = env('GOOGLE_SERVICE_ACCOUNT_JSON', default='')
TERRITORY_CARDS_MASTER_SHEET_ID = env('TERRITORY_CARDS_MASTER_SHEET_ID', default='')

# ─────────────────────────────────────────────────────────────
# board (회중게시판 = 구글드라이브 폴더) 연동 설정
# 위와 같은 서비스 계정으로 Drive API(메타데이터 읽기 전용)에 접근한다.
#   CONGREGATION_BOARD_FOLDER_ID : 회중게시판 폴더의 folderId
# 폴더를 서비스 계정 이메일에 '뷰어'로 공유 + GCP 에서 Drive API 활성화 필요.
# ─────────────────────────────────────────────────────────────
CONGREGATION_BOARD_FOLDER_ID = env('CONGREGATION_BOARD_FOLDER_ID', default='')

# LINE 인앱 브라우저(WebView)에서 세션/CSRF 쿠키가 유지되도록 하는 정책.
# LINE 앱은 미니앱을 서드파티 컨텍스트의 WebView 로 열기 때문에, SameSite=None 이 아니면
# 세션 쿠키가 요청에 실리지 않아 로그인이 바로 풀린다. SameSite=None 은 반드시
# Secure(HTTPS)와 함께여야 브라우저가 쿠키를 저장한다.
#
# 적용 조건:
#   - 프로덕션(DEBUG=False), 또는
#   - LINE 로그인이 설정된 경우(LINE_LOGIN_ENABLED) — LIFF 는 HTTPS 필수이므로
#     ngrok 등 HTTPS 터널 뒤에서 DEBUG=True 로 실연동 테스트할 때도 켜져야 한다.
# 환경변수 WEBVIEW_COOKIES=0/1 로 강제 override 할 수 있다.
# (SECURE_PROXY_SSL_HEADER 가 이미 설정되어 있어 ngrok/PA 프록시 뒤에서도 request.is_secure() 가 True)
_webview_cookies_env = os.environ.get('WEBVIEW_COOKIES')
if _webview_cookies_env is not None:
    WEBVIEW_COOKIES = _webview_cookies_env == '1'
else:
    WEBVIEW_COOKIES = (not DEBUG) or LINE_LOGIN_ENABLED

if WEBVIEW_COOKIES:
    SESSION_COOKIE_SAMESITE = 'None'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = 'None'
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'apps.territory',
    'apps.member',
    'apps.deck',
    'apps.manager',
    'apps.line',
    'apps.territory_cards',
    'apps.board',
    'apps.home',
    'apps.bible_reading',
    'apps.character_quiz',
    'django_extensions',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    'crispy_bootstrap5',
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'apps.line.middleware.LIFFContextMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tsk.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'tsk.context_processors.site_meta',
            ],
        },
    },
]

WSGI_APPLICATION = 'tsk.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Member 모델을 Django User모델과 통합
AUTH_USER_MODEL = 'member.Member'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 사용자 업로드 파일(admin 의 Flex 메뉴 타일 이미지 등).
# 운영(PA)에서는 /media/ → 이 디렉토리로 static files 매핑을 추가해야 한다.
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
