# Generated by Django 5.2.1 on 2026-07-14 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LineProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=64, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('picture_url', models.URLField(blank=True)),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='line_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
