# Generated by Django 5.2.1 on 2026-08-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0002_linelinkcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50, unique=True, verbose_name='키워드')),
                ('active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '봇 키워드',
                'verbose_name_plural': '봇 키워드',
            },
        ),
    ]
