# Generated by Django 5.2.1 on 2026-08-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0004_seed_bot_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, verbose_name='이름')),
                ('link', models.CharField(help_text='사이트 내부 경로(예: /cards/)는 LIFF 로그인을 거쳐 열립니다. https:// 로 시작하면 그대로 사용(외부 링크).', max_length=300, verbose_name='링크')),
                ('image', models.ImageField(help_text='권장 크기 — 상단: 1200x405, 하단: 400x405. 비율이 다르면 잘려 보입니다.', upload_to='flex_menu/', verbose_name='타일 이미지')),
                ('row', models.CharField(choices=[('hero', '상단(전폭)'), ('bottom', '하단(분할)')], default='bottom', max_length=10, verbose_name='배치')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='같은 배치 안에서의 정렬(작을수록 먼저)', verbose_name='순서')),
                ('active', models.BooleanField(default=True, verbose_name='활성')),
            ],
            options={
                'verbose_name': '봇 메뉴 타일',
                'verbose_name_plural': '봇 메뉴 타일',
                'ordering': ['order', 'id'],
            },
        ),
    ]
