# Generated by Django 5.2.1 on 2026-08-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0006_seed_bot_menu_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='botkeyword',
            name='action',
            field=models.CharField(choices=[('menu', '전체 메뉴'), ('today_reading', '오늘의 성서 읽기')], default='menu', help_text="이 키워드에 봇이 어떻게 답할지. '오늘의 성서 읽기'는 보낸 사람의 다음 읽기 부분을 답합니다.", max_length=20, verbose_name='동작'),
        ),
    ]
