# Generated by Django 5.2.1 on 2026-08-11 14:15
"""action 값 개명: today_reading → bible_reading (표시명 '성경통독').

'today_reading' 이름을 다른 용도로 쓰기 위해 비움. 0008 로 시드된 기존 행의
값도 함께 갱신한다(테스트머신 등 이미 적용된 DB 대응).
"""

from django.db import migrations, models


def rename_action_value(apps, schema_editor):
    BotKeyword = apps.get_model("line", "BotKeyword")
    BotKeyword.objects.filter(action="today_reading").update(action="bible_reading")


def unrename_action_value(apps, schema_editor):
    BotKeyword = apps.get_model("line", "BotKeyword")
    BotKeyword.objects.filter(action="bible_reading").update(action="today_reading")


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0008_seed_today_reading_keyword'),
    ]

    operations = [
        migrations.RunPython(rename_action_value, unrename_action_value),
        migrations.AlterField(
            model_name='botkeyword',
            name='action',
            field=models.CharField(choices=[('menu', '전체 메뉴'), ('bible_reading', '성경통독')], default='menu', help_text="이 키워드에 봇이 어떻게 답할지. '성경통독'은 보낸 사람의 다음 읽기 부분을 답합니다.", max_length=20, verbose_name='동작'),
        ),
    ]
