# Generated by Django 5.2.1 on 2026-08-11 14:51
"""action 2종 추가(daily_text/weekly_reading) + 키워드 정비.

키워드를 성경통독/일용할성구/주간성서읽기 트리오로 통일한다:
- 0008 이 시드한 옛 키워드(오늘성서읽기/오늘의성서읽기)는 삭제하고
  같은 동작(bible_reading)의 '성경통독' 으로 교체
- 일용할성구(daily_text)/주간성서읽기(weekly_reading) 신규 시드
"""

from django.db import migrations, models

OLD_WORDS = ("오늘성서읽기", "오늘의성서읽기")
SEEDS = [
    ("성경통독", "bible_reading"),
    ("일용할성구", "daily_text"),
    ("주간성서읽기", "weekly_reading"),
]


def seed(apps, schema_editor):
    BotKeyword = apps.get_model("line", "BotKeyword")
    BotKeyword.objects.filter(word__in=OLD_WORDS).delete()
    for word, action in SEEDS:
        BotKeyword.objects.get_or_create(
            word=word, defaults={"active": True, "action": action}
        )


def unseed(apps, schema_editor):
    BotKeyword = apps.get_model("line", "BotKeyword")
    BotKeyword.objects.filter(word__in=[w for w, _ in SEEDS]).delete()
    for word in OLD_WORDS:
        BotKeyword.objects.get_or_create(
            word=word, defaults={"active": True, "action": "bible_reading"}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0009_alter_botkeyword_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botkeyword',
            name='action',
            field=models.CharField(choices=[('menu', '전체 메뉴'), ('bible_reading', '성경통독'), ('daily_text', '일용할 성구'), ('weekly_reading', '주간 성서 읽기')], default='menu', help_text="이 키워드에 봇이 어떻게 답할지. '성경통독'은 보낸 사람의 다음 읽기 부분을 답합니다.", max_length=20, verbose_name='동작'),
        ),
        migrations.RunPython(seed, unseed),
    ]
