# Generated by Django 5.2.1 on 2026-08-16 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0010_alter_botkeyword_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='botkeyword',
            name='action',
            field=models.CharField(choices=[('menu', '전체 메뉴'), ('bible_reading', '성경통독'), ('daily_text', '일용할 성구'), ('weekly_reading', '주간 성서 읽기'), ('daily_text_stamp', '성구 스탬프 카드'), ('daily_text_report', '성구 월말 정산')], default='menu', help_text="이 키워드에 봇이 어떻게 답할지. '성경통독'은 보낸 사람의 다음 읽기 부분을 답합니다.", max_length=20, verbose_name='동작'),
        ),
        migrations.CreateModel(
            name='DailyTextParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_per_check', models.PositiveIntegerField(default=0, help_text="정산 때 '횟수 × 단가'로 계산합니다(화폐 단위 없이 숫자만).", verbose_name='회당 단가')),
                ('perfect_month_bonus', models.PositiveIntegerField(default=0, help_text='한 달을 하루도 빠짐없이 체크하면 정산에 더해지는 금액.', verbose_name='개근 보너스')),
                ('active', models.BooleanField(default=True, verbose_name='활성')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_text_participant', to=settings.AUTH_USER_MODEL, verbose_name='멤버')),
            ],
            options={
                'verbose_name': '일용할 성구 참여자',
                'verbose_name_plural': '일용할 성구 참여자',
            },
        ),
        migrations.CreateModel(
            name='DailyTextCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_text_checks', to=settings.AUTH_USER_MODEL, verbose_name='멤버')),
            ],
            options={
                'verbose_name': '일용할 성구 체크',
                'verbose_name_plural': '일용할 성구 체크',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('member', 'date'), name='unique_daily_text_check_per_day')],
            },
        ),
    ]
