# Generated by Django 5.2.1 on 2026-08-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0012_seed_daily_text_check_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='StampManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '성구 스탬프',
                'verbose_name_plural': '성구 스탬프 관리',
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
    ]
