# Generated by Django 5.2.1 on 2026-08-22 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0013_stampmanagement'),
        # 삭제 전에 데이터가 messenger 쪽으로 복사돼 있어야 한다(순서 보장).
        ('messenger', '0002_copy_from_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='LineLinkCode',
        ),
        migrations.DeleteModel(
            name='LineProfile',
        ),
    ]
