# Generated by Django 5.2.1 on 2026-09-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('line', '0014_remove_lineprofile_user_delete_linelinkcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botkeyword',
            name='action',
            field=models.CharField(choices=[('menu', '전체 메뉴'), ('bible_reading', '성경통독'), ('daily_text', '일용할 성구'), ('weekly_reading', '주간 성서 읽기'), ('daily_text_stamp', '성구 스탬프 카드'), ('daily_text_report', '성구 월말 정산'), ('help', '도움말 (발신자 맞춤 키워드 안내, 1:1 전용)')], default='menu', help_text="이 키워드에 봇이 어떻게 답할지. '성경통독'은 보낸 사람의 다음 읽기 부분을 답합니다.", max_length=20, verbose_name='동작'),
        ),
    ]
