# Generated by Django 5.2.1 on 2026-08-30 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodedAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, unique=True, verbose_name='지오코딩 주소')),
                ('lat', models.FloatField(verbose_name='위도')),
                ('lng', models.FloatField(verbose_name='경도')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='갱신일시')),
            ],
            options={
                'verbose_name': '지오코딩 좌표 캐시',
                'verbose_name_plural': '지오코딩 좌표 캐시',
            },
        ),
    ]
