# Generated by Django 5.2.1 on 2026-10-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territory_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcludedCardFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='드라이브에 보이는 파일 이름 그대로(정확히 일치하면 제외 — 파일을 개명하면 여기도 고쳐 주세요).', max_length=200, unique=True, verbose_name='파일 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
            ],
            options={
                'verbose_name': '구역카드 제외 파일',
                'verbose_name_plural': '구역카드 제외 파일',
                'ordering': ('name',),
            },
        ),
    ]
