# Generated by Django 5.2.1 on 2026-08-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '인물카드',
                'verbose_name_plural': '인물카드 관리',
                'managed': False,
                'default_permissions': ('view',),
            },
        ),
    ]
